-- EstateHub AI - Supabase PostgreSQL schema
-- Run this file in Supabase SQL Editor.

create table if not exists properties (
    id text primary key,
    title text not null,
    property_type text not null,
    location text not null,
    price numeric(14,2) not null,
    bedrooms integer default 0,
    area_sqft numeric(10,2),
    furnishing text default '',
    amenities text[] default '{}',
    distance_km numeric(8,2)
);

create table if not exists clients (
    id bigint generated by default as identity primary key,
    name text not null,
    contact text default ''
);

create table if not exists property_inquiries (
    id bigint generated by default as identity primary key,
    client_id bigint not null references clients(id) on delete cascade,
    location text not null,
    property_type text default '',
    budget numeric(14,2),
    purpose text default '',
    status text default 'active'
);

create table if not exists property_visits (
    id bigint generated by default as identity primary key,
    property_id text not null references properties(id) on delete cascade,
    client_id bigint references clients(id) on delete set null,
    visit_date date not null,
    visit_time time not null,
    status text default 'scheduled'
);

create table if not exists search_history (
    id bigint generated by default as identity primary key,
    client_id bigint references clients(id) on delete set null,
    query text not null,
    created_at timestamptz default now()
);

insert into properties (id,title,property_type,location,price,bedrooms,area_sqft,furnishing,amenities,distance_km)
values
('P001','Demo Marina Heights','Apartment','Chennai',6500000,2,1100,'Semi-Furnished',array['Parking','Gym','Security'],3.2),
('P002','Demo OMR Residency','Apartment','Chennai',8500000,3,1450,'Fully Furnished',array['Parking','Pool','Gym'],5.1),
('P003','Demo Tambaram Villa','Villa','Chennai',11500000,3,1800,'Semi-Furnished',array['Garden','Parking','Security'],7.4),
('P004','Demo City Office Space','Commercial','Chennai',12000000,0,2200,'Unfurnished',array['Parking','Power Backup','Lift'],4.6)
on conflict (id) do update set
 title=excluded.title,
 property_type=excluded.property_type,
 location=excluded.location,
 price=excluded.price,
 bedrooms=excluded.bedrooms,
 area_sqft=excluded.area_sqft,
 furnishing=excluded.furnishing,
 amenities=excluded.amenities,
 distance_km=excluded.distance_km;
